apiVersion: v1
kind: Secret
metadata:
  name: postgresql-postgresql
  labels:
    app: postgresql
    chart: postgresql-2.6.6
    release: "postgresql"
    heritage: "Tiller"
type: Opaque
data:
  postgresql-password: "FORKED_PASSWORD"
