apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    chart: postgresql-2.6.6
    heritage: Tiller
    release: postgresql
  name: postgresql-postgresql-headless
spec:
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: postgresql
    release: postgresql
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    chart: postgresql-2.6.6
    heritage: Tiller
    release: postgresql
  name: postgresql-postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: postgresql
    release: postgresql
    role: master
  type: ClusterIP
