dependencies:
- name: elasticsearch
  version:  1.16.0
  repository: file://../elasticsearch
- name: kibana
  version: 1.1.2
  repository: file://../kibana
- name: logstash
  version: 1.4.2
  repository: file://../logstash
  condition: logstash.enabled
