dependencies:
- name: elasticsearch
  version: ^1.10.0
  repository: file://../elasticsearch
- name: kibana
  version: 1.1.2
  repository: file://../kibana
- name: logstash
  version: ^1.2.1
  repository: file://../logstash
  condition: logstash.enabled
